apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: px-delivery
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: px-db
  resources:
    requests:
      storage: 30Gi